ie3-institute/PowerSystemUtils

gradle/scripts/mavenCentralPublish.gradle
gradle/scripts/selfContainedJar.gradle

Adding main contributors to maven central publish and altering the name of a fat jar

adaptingGradleScripts

---

README.md

ie3-institute/PowerSystemUtils#11

---

src/main/java/edu/ie3/util/io/FileIOUtils.java
src/test/groovy/edu/ie3/util/io/FileHelperTest.groovy

Transfer of some new methods that simplify I/O operations on files. 
addresses #13

Add more methods to FileHelper

---

src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java

Introduce µS/km as own unit

---

Jenkinsfile
src/main/java/edu/ie3/util/TimeTools.java
src/main/java/edu/ie3/util/TimeUtil.java
src/test/groovy/edu/ie3/util/TimeUtilsTest.groovy

solves #18 
I did not transfer some TimeTools methods to the new TimeUtil as they seemed to be not very useful as well as dangerous implemented. Pls check if you're missing some of them and let me know. 
- market TimeTools as deprecated
- added tests for TimeUtil
- fixes a sonarqube issue in Jenkinsfile

New TimeUtil

---

src/main/java/edu/ie3/util/quantities/QuantityUtil.java
src/test/groovy/edu/ie3/util/quantities/QuantityUtilTest.groovy

Introducing a QuantityUtil that is able to make Quantities comparable

---

src/main/java/edu/ie3/util/TimeUtil.java

Currently, the class is package private. 😢

Let the beast (TimeUtil) out of its cage

---

build.gradle
src/main/java/edu/ie3/util/StringUtils.java
src/main/java/edu/ie3/util/geo/GeoUtils.java
src/test/groovy/edu/ie3/util/StringUtilsTest.groovy
src/test/groovy/edu/ie3/util/geo/GeoUtilsTest.groovy

Consolidate and enhance GeoUtils

---

src/main/java/edu/ie3/util/StringUtils.java
src/test/groovy/edu/ie3/util/StringUtilsTest.groovy

- extended StringUtils with methods for snakeCaseTo(Pascal|Camel)Case()
- added corresponding tests

extended StringUtils 

---

build.gradle

- increased version to 1.3.2-SNAPSHOT after 1.3.1 release
- minor change in build.gradle 
- fmt

increased version to 1.3.2-SNAPSHOT 

---

src/main/java/edu/ie3/util/quantities/QuantityUtil.java
src/test/groovy/edu/ie3/util/quantities/QuantityUtilTest.groovy

transfer of the until now internal `QuantityUtil.considerablyAbsEqual(...)` and `QuantityUtil.considerablyRelEqual(...)` to its correct util class

added two new methods to QuantityUtil

---

build.gradle
src/main/java/edu/ie3/util/quantities/QuantityUtil.java
src/test/groovy/edu/ie3/util/quantities/QuantityUtilTest.groovy

Compare angles by their repetitive nature

---

CHANGELOG.md

Include semantic CHANGELOG document

---

CHANGELOG.md
src/main/java/edu/ie3/util/OneToOneMap.java
src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java
src/test/groovy/edu/ie3/util/OneToOneMapTest.groovy

Improve implementation of unit 'p.u.'

---

src/main/java/edu/ie3/util/quantities/QuantityUtil.java
src/test/groovy/edu/ie3/util/quantities/QuantityUtilTest.groovy

fixes #49 
Please check if you feel like those default values are fitting!

Added tolerances and convenience methods, fixed equality check

---

build.gradle

Just the build.gradle file adaption to switch to 1.5-SNAPSHOT

adapted build.gradle for 1.5-SNAPSHOT

---

CHANGELOG.md
src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java
src/main/java/edu/ie3/util/quantities/interfaces/EnergyDensity.java
src/main/java/edu/ie3/util/quantities/interfaces/PowerDensity.java

Changed irradiation's dimension to Power/Area

---

src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java
src/test/groovy/edu/ie3/util/quantities/PowerSystemUnitsTest.groovy

Fix malicious implementation of degree unit

---

src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java
src/main/java/edu/ie3/util/quantities/interfaces/EnergyDensity.java
src/main/java/edu/ie3/util/quantities/interfaces/Irradiance.java
src/main/java/edu/ie3/util/quantities/interfaces/Irradiation.java
src/main/java/edu/ie3/util/quantities/interfaces/PowerDensity.java

Fix Irradiation/Irradiance

---

CHANGELOG.md
build.gradle
gradle/wrapper/gradle-wrapper.properties

Set dependency version to fixed version

---

src/main/java/edu/ie3/util/geo/CoordinateDistance.java
src/test/groovy/edu/ie3/util/geo/CoordinateDistanceTest.groovy

Test for CoordinateDistance

---

CHANGELOG.md
build.gradle
src/main/java/edu/ie3/util/StreamUtils.java
src/main/java/edu/ie3/util/StringUtils.java
src/main/java/edu/ie3/util/copy/DeepCopy.java
src/main/java/edu/ie3/util/geo/GeoUtils.java

prepare for v1.5 release

---

CHANGELOG.md
build.gradle
src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java
src/test/groovy/edu/ie3/util/quantities/PowerSystemUnitsTest.groovy

Fix malicious implementation of units

---

build.gradle

set version back to 1.6-SNAPSHOT

---

CHANGELOG.md
build.gradle
src/main/java/edu/ie3/util/StringUtils.java
src/main/java/edu/ie3/util/naming/Naming.java
src/main/java/edu/ie3/util/naming/NamingConvention.java
src/test/groovy/edu/ie3/util/StringUtilsTest.groovy
src/test/groovy/edu/ie3/util/naming/NamingTest.groovy

Add a class that aids in providing namings in different naming conventions

---

build.gradle

back to snap shot

---

CHANGELOG.md
build.gradle

Hot fix information vulnerability

---

build.gradle

Set back version number. Is blocked by #111

Reset version to snapshot

---

src/main/java/edu/ie3/util/io/FileIOUtils.java

... to compress long files and those with big numbers.

Allow usage of POSIX tar-extension

---

Jenkinsfile
build.gradle
gradle/scripts/modernizer.gradle
gradle/scripts/selfContainedJar.gradle
gradle/scripts/sonarqube.gradle

Remove duplicate properties

---

CHANGELOG.md
build.gradle
src/main/java/edu/ie3/util/OneToOneMap.java
src/main/java/edu/ie3/util/io/xmladapter/StringToIntegerListAdapter.java
src/main/java/edu/ie3/util/io/xmladapter/StringToStringListAdapter.java
src/main/java/edu/ie3/util/io/xmladapter/YearAdapter.java

This branch triggers a release for v1.6.0
This release will be the last one with java 8 support.
Resolves #196

Release v1.6.0

---

src/main/java/edu/ie3/util/copy/FastByteArrayOutputStream.java
src/main/java/edu/ie3/util/geo/GrahamScan.java

Fix (most severe) JavaDoc issues

---

Jenkinsfile

Fix deployment

---

build.gradle
src/main/scala/edu/ie3/util/osm/OsmUtils.scala
src/main/scala/edu/ie3/util/osm/model/RichClosedWaySupport.scala
src/test/scala/edu/ie3/util/osm/OsmUtilsSpec.scala
src/test/scala/edu/ie3/util/osm/SimpleOsmTestData.scala

Resolves #239 
Turns out the Scala compiler played a trick on me. The functionality I was looking for is still there though it was missing the conversion from closed way to polygon which I added

add build polygon functionality

---

src/test/scala/edu/ie3/util/geo/RichGeometriesSpec.scala

refactor test

---

Jenkinsfile
build.gradle
gradle/scripts/scoverage.gradle
gradle/scripts/sonarqube.gradle
src/main/scala/edu/ie3/util/exceptions/OsmException.scala
src/main/scala/edu/ie3/util/osm/OsmContainerUtils.scala
src/main/scala/edu/ie3/util/osm/OsmUtils.scala
src/main/scala/edu/ie3/util/osm/model/CommonOsmKey.scala
src/main/scala/edu/ie3/util/osm/model/OsmContainer.scala
src/main/scala/edu/ie3/util/osm/model/OsmEntity.scala
src/main/scala/edu/ie3/util/osm/model/RelationEntitiesSupport.scala
src/main/scala/edu/ie3/util/osm/model/RichClosedWaySupport.scala
src/main/scala/edu/ie3/util/osm/model/WayCache.scala
src/test/scala/edu/ie3/util/osm/OsmContainerUtilsSpec.scala
src/test/scala/edu/ie3/util/osm/OsmUtilsSpec.scala
src/test/scala/edu/ie3/util/osm/model/OsmContainerSpec.scala

Resolves #250 
Since we do not want to upgrade Scala in SIMONA to 3 yet, we need to keep PSU at 2.13 anyways.

Downgrade to scala 2.13

---

src/main/java/edu/ie3/util/geo/GeoUtils.java
src/main/scala/edu/ie3/util/quantities/QuantityUtils.scala
src/test/groovy/edu/ie3/util/geo/GeoUtilsTest.groovy
src/test/scala/edu/ie3/util/quantities/QuantityUtilsSpec.scala

To/#276 #245 add util functions

---

CHANGELOG.md
src/main/scala/edu/ie3/util/quantities/QuantityUtils.scala
src/test/scala/edu/ie3/util/quantities/QuantityUtilsSpec.scala

add quantity functionality

---

CHANGELOG.md
README.md
gradle/scripts/mavenCentralPublish.gradle

Updating badges and license link

---

CHANGELOG.md
src/main/java/edu/ie3/util/exceptions/QuantityException.java
src/main/java/edu/ie3/util/quantities/MetricPrefixDouble.java
src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java
src/main/scala/edu/ie3/util/quantities/QuantityUtils.scala
src/test/groovy/edu/ie3/util/quantities/MetricPrefixDoubleTest.groovy
src/test/scala/edu/ie3/util/quantities/QuantityUtilsSpec.scala

Introducing MetricPrefixDouble, creating unit conversions that use double factors

---

CHANGELOG.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/edu/ie3/util/EmpiricalRandom.java
src/main/java/edu/ie3/util/OneToOneMap.java

Release version 2.0

---

Jenkinsfile
gradle/scripts/mavenCentralPublish.gradle

Improved Jenkinsfile security, updated login

---

gradle/scripts/mavenCentralPublish.gradle

Moved to a different sonatype instance

---

CHANGELOG.md
src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java
src/main/java/edu/ie3/util/quantities/interfaces/VolumetricFlowRate.java

Added VolumetricFlowRate

---

.gitignore
src/main/java/edu/ie3/util/TimeUtil.java

Correct Local Date Time Parsing

---

CHANGELOG.md
src/main/java/edu/ie3/util/TimeUtil.java
src/test/groovy/edu/ie3/util/TimeUtilTest.groovy

Resolves #422 
Please discuss the issue here. This is how I feel the method should work. Other opinions?

Fixing TimeUtil parsing ZonedDateTimes

---

CHANGELOG.md
build.gradle

Release 2.1

---

src/main/java/edu/ie3/util/TimeUtil.java
src/test/groovy/edu/ie3/util/TimeUtilTest.groovy

Remove unused fields from TimeUtil

---

CHANGELOG.md
build.gradle
gradle/scripts/scoverage.gradle
src/main/scala/edu/ie3/util/DoubleUtils.scala
src/main/scala/edu/ie3/util/geo/RichGeometries.scala
src/main/scala/edu/ie3/util/osm/model/OsmEntity.scala
src/main/scala/edu/ie3/util/quantities/QuantityUtils.scala
src/test/scala/edu/ie3/util/DoubleUtilsSpec.scala
src/test/scala/edu/ie3/util/geo/RichGeometriesSpec.scala
src/test/scala/edu/ie3/util/quantities/QuantityUtilsSpec.scala

Upgrade to `scala3`.

---

CHANGELOG.md
build.gradle
gradle/scripts/mavenCentralPublish.gradle

Fixing missing sources in releases.
